tgstation-operations/infrastructure

README.md

today i woke up and thought, hm.... what if i stole @Lorwp's CI runners

Fixes badge pointing to the wrong repo

---

systems/game-servers/modules/garage.nix
systems/game-servers/modules/tgs/default.nix
systems/game-servers/systems/tgsatan/default.nix

Also adds the missing motd back to satan, oof.

Add missing dependencies (Mainly tailscaled)

---

systems/game-servers/modules/tgs/tgs_config.yml

It has so many cool features and dominion promised it will stop byond hanging.

Bump the tgs version to 5.5.0

---

systems/edge-nodes/modules/caddy.nix
systems/edge-nodes/secrets/cloudflare_api.age
systems/edge-nodes/secrets/phpbb_db.age
systems/edge-nodes/secrets/secrets.nix
systems/edge-nodes/secrets/tailscaleAuthKey.age

Rekeys edge node secrets as well.
Required DB bits are already set, this will require DNS to be done when merged though (which i'll do)

Add phpbb to frontend edge node (lime)

---

modules/base.nix

Scriptis pointed out a comment would be a good idea and I agree

Network wait online comment

---

systems/game-servers/systems/tgsatan/modules/redbot.nix

Redbot fix

---

systems/game-servers/systems/tgsatan/default.nix

Fixes attic being nuked on reboots. oops.

Persist postgres on tgsatan

---

systems/edge-nodes/modules/caddy.nix

hopefully this makes them show up in mediawiki's env

Add env vars to Caddy's MediaWiki config

---

modules/users/operator/default.nix
modules/users/operator/ivory.nix
systems/vpn/modules/headscale/headscale-acl.json

Add ivory as a server operator

---

systems/game-servers/modules/maria.nix

thread pool would basically be required with the amount of connections

Enables thread pool and doubles max connections in MariaDB

---

systems/edge-nodes/modules/caddy.nix

didnt know that these things were scoped, hopefully moving them to the end of the file fixes the issue (please let there be hoisting)

Fix caddy error

---

systems/edge-nodes/modules/caddy.nix

skin resources currently 404 because they arent matched by the regex correctly

Fix skin resource files not loading correctly

---

systems/edge-nodes/modules/caddy.nix

also removing xdebug because we dont need it anymore

Memcached for MediaWiki

---

systems/vpn/modules/headscale/headscale-acl.json

Add rex9001 to keyholders

---

flake.lock
systems/edge-nodes/systems/staging/modules/caddy.nix

Fix server info fetcher on staging hopefully

---

.github/workflows/auto_approve_website_prs.yml
.github/workflows/colmena.yml
.github/workflows/website_sync.yml

Creates a PR with a targeted flake update, approves, and automerges

Automatic website updating workflow

---

modules/tailscale.nix

See https://github.com/tailscale/tailscale/issues/11504

Try this workaround for tailscale not waiting for DHCP

---

modules/tailscale.nix

Reverts tgstation-operations/infrastructure#117
Broke staging

Revert "Try this workaround for tailscale not waiting for DHCP"

---

systems/edge-nodes/modules/caddy.nix
systems/edge-nodes/systems/staging/modules/caddy.nix

mainly to fix phpbb spambot bans

Add CF-Connecting-IP to caddy configs

---

systems/edge-nodes/modules/caddy.nix
systems/edge-nodes/systems/us-lime.nix

Add imagemagick to lime's system packages

---

.github/workflows/colmena_deploy.yml

Fix stupid mistake in colmena deploy workflow

---

systems/game-servers/modules/tgs/EventScripts/tg/update-config.sh

its a toml file ever since melbert made his rework of dynamic, pretty simple.

Dynamic's config is not copied over now, lets fix that.

---

systems/game-servers/modules/tgs/default.nix

I did an oopsie and forgot these lines.

webedit ops 3: return of the caffeine

---

.github/FUNDING.yml
.github/workflows/colmena.yml
.github/workflows/colmena_deploy.yml
.github/workflows/dependencies_sync.yml
flake.lock
flake.nix

Set it up to auto-update properly

I forgot to update the flake revision
